# Generated by Django 4.2 on 2023-05-08 11:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_modules_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
