# Generated by Django 4.2 on 2023-05-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='course',
        ),
        migrations.AddField(
            model_name='category',
            name='course',
            field=models.CharField(default='names', max_length=250),
        ),
    ]
