# Generated by Django 4.2 on 2023-05-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_category_course_category_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='course',
        ),
        migrations.AddField(
            model_name='category',
            name='course',
            field=models.ManyToManyField(related_name='categories', to='main.course'),
        ),
    ]
