# Generated by Django 4.2 on 2023-05-17 17:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_modules_intro_quiz_qquestions_qanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
