# Generated by Django 4.2 on 2023-05-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='cateogory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.category'),
        ),
    ]
