# Generated by Django 4.2 on 2023-05-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_category_uuid_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cateogory',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='resource',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.FileField(upload_to='modules_resource/%y')),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modules')),
            ],
        ),
    ]
