# Generated by Django 4.2 on 2023-05-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cateogory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.category'),
        ),
    ]
