# Generated by Django 4.2 on 2023-05-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_resource_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
