# Generated by Django 4.2 on 2023-05-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_resource_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cateogory',
            new_name='category',
        ),
    ]
