# Generated by Django 4.2 on 2023-06-21 09:24

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_course_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubModules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("body", django_quill.fields.QuillField(max_length=1000000)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SubModules",
                        to="main.modules",
                    ),
                ),
            ],
        ),
    ]
